kind: project
metadata:
  name: stocks-dani
spec:
  functions: []
  workflows: []
  artifacts: []
  artifact_path: v3io:///projects/{{run.project}}/artifacts
  source: ''
  subpath: ''
  origin_url: ''
  desired_state: online
