kind: project
metadata:
  name: stocks-dani
spec:
  params:
    PROJECT_NAME: stocks-dani
    ARTIFACT_PATH: v3io:///projects/{{run.project}}/artifacts
  functions:
  - url: code/00-train-sentiment-analysis-model.ipynb
    name: bert_sentiment_classifier_trainer
    kind: job
  - url: code/01-function_invoker.ipynb
    name: func_invoke
    kind: job
  - url: code/02-read-stocks.ipynb
    name: stocks_reader
    kind: nuclio
    image: mlrun/mlrun:0.6.5
  - url: code/03-read-news.ipynb
    name: news_reader
    kind: nuclio
    image: mlrun/mlrun:0.6.5
  - url: code/04-stream-viewer.ipynb
    name: stream_viewer
    kind: nuclio
    image: mlrun/mlrun:0.6.5
  - url: hub://sentiment_analysis_serving
    name: sentiment_analysis_server
  - url: code/05-read-vector.ipynb
    name: vector_reader
    kind: nuclio
    image: mlrun/mlrun:0.6.5
  - url: code/06-model_training.ipynb
    name: rnn_model_training
    kind: nuclio
    image: mlrun/ml-models-gpu
  - url: code/07-model_prediction.ipynb
    name: rnn_model_prediction
    kind: nuclio
    image: mlrun/mlrun:0.6.5
  - url: code/08-grafana.ipynb
    name: grafana_view
    kind: job
    image: mlrun/mlrun:0.6.5
  - url: hub://rnn_serving
    name: rnn_serving
    kind: serving
  workflows:
  - name: main
    path: /User/test/demos/stock-analysis/code/workflow.py
    engine: kfp
  artifacts: []
  source: ''
  subpath: ''
  origin_url: ''
  desired_state: online
